export default {
    products: [{
            _id: "1",
            name: "Full Zip Running Shirts",
            category: "Shirts",
            image: "/images/product-1.jpg",
            price: 60,
            brand: "Hiskywin",
            rating: 4.5,
            numberReviews: 10,
            countInStock: 6,
        },
        {
            _id: "2",
            name: "Nike Full-Zip Hoddie Mens Workout Swearshirt",
            category: "Shirts",
            image: "/images/product-2.jpg",
            price: 70,
            brand: "Nike",
            rating: 5,
            numberReviews: 51,
            countInStock: 9,

        }, {
            _id: "3",
            name: "Adidas Mens Long Sleeve Hoodie",
            category: "Shirts",
            image: "/images/product-3.jpg",
            price: 59,
            brand: "Adidas",
            rating: 4,
            numberReviews: 45,
            countInStock: 14,
        }, {
            _id: "4",
            name: "Under Armour Mens Sportstyle Tricot Joggers",
            category: "Pants",
            image: "/images/product-4.jpg",
            price: 90,
            brand: "Under Armour",
            rating: 2.5,
            numberReviews: 198,
            countInStock: 8
        }, {
            _id: '5',
            name: "Champions Mens Graphic Powerblend Fleece Jogger",
            category: "Pants",
            image: '/images/product-5.jpg',
            price: 119,
            brand: "Champion",
            rating: 3.5,
            numberReviews: 89,
            countInStock: 6,
        }, {
            _id: "6",
            name: "Aelfric Eden Mens Jodders Pants Long Multi-Pocket",
            category: "Pants",
            image: "/images/product-6.jpg",
            price: 85,
            rating: 4.5,
            numberReviews: 45,
            countInStock: 8,
        }
    ]
}